# Generated by Django 4.1.4 on 2023-01-07 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shop Name', max_length=25)),
                ('url', models.CharField(default='Link Website for Shop', max_length=50)),
                ('password', models.CharField(default='Password add Shop', max_length=7)),
                ('open_hour', models.IntegerField(default=8)),
                ('close_hour', models.IntegerField(default=20)),
                ('message', models.CharField(default='Message notification', max_length=150)),
                ('lat', models.FloatField(default=0.0, max_length=10)),
                ('lng', models.FloatField(default=0.0, max_length=10)),
                ('distance', models.IntegerField(default=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
