# Generated by Django 4.1.4 on 2023-01-29 00:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='List shop Name', max_length=25)),
                ('password', models.CharField(default='Password for list shop', max_length=7, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Shop Name', max_length=25)),
                ('url', models.CharField(default='Link Website for Shop', max_length=50)),
                ('password', models.CharField(default='Password add Shop', max_length=7, unique=True)),
                ('open_hour', models.IntegerField(default=8)),
                ('close_hour', models.IntegerField(default=20)),
                ('message', models.CharField(default='Message notification', max_length=150)),
                ('google_maps', models.CharField(default='Link Google Maps', max_length=300)),
                ('lat', models.FloatField(default=0.0, max_length=10)),
                ('lng', models.FloatField(default=0.0, max_length=10)),
                ('distance', models.IntegerField(default=150)),
                ('shop_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.shopgroup')),
            ],
        ),
    ]
