# Generated by Django 4.1.4 on 2023-01-30 12:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_shopgroup_options_alter_shop_close_hour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='open_hour',
            field=models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(0, message='Opening time must be between 0h and 23h'), django.core.validators.MaxValueValidator(23, message='Opening time must be between 0h and 23h')]),
        ),
    ]
