# Generated by Django 4.1.4 on 2023-01-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_shop_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='google_maps',
            field=models.CharField(default='Link Google Maps', max_length=300),
        ),
    ]
