# Generated by Django 4.1.4 on 2023-01-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_shop_google_maps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='password',
            field=models.CharField(default='Password add Shop', max_length=7, unique=True),
        ),
    ]
