# Generated by Django 4.1.4 on 2023-02-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_shop_open_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='google_maps',
            field=models.CharField(default='Link Google Maps', max_length=600),
        ),
        migrations.AlterField(
            model_name='shop',
            name='url',
            field=models.CharField(default='Link Website for Shop', max_length=500),
        ),
    ]
