# Generated by Django 4.1.4 on 2023-02-27 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_shop_google_maps_alter_shop_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='message_two',
            field=models.CharField(default='Message notification 0m Distance', max_length=150),
        ),
    ]
