# Generated by Django 4.1.4 on 2023-02-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_shop_message_two'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='url_two',
            field=models.CharField(default='Link Website for Shop', max_length=500),
        ),
    ]
