# Generated by Django 4.1.4 on 2023-01-20 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='expired',
        ),
    ]
