# Generated by Django 4.1.4 on 2023-01-21 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('push_notification', '0002_remove_notification_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='image',
        ),
    ]
